language: java
jdk:
  - oraclejdk11
  - openjdk11
  - openjdk10
  - oraclejdk8
  - openjdk8
sudo: false
install: mvn dependency:resolve --batch-mode --show-version --settings .travis.settings.xml
script:
  - mvn test
  - mvn javadoc:javadoc
  - mvn package