language: node_js
node_js:
  - node
services: docker
sudo: false

before_install: |
  cd ../ &&
  mv RedditToTelegram/ rtt/ &&
  cd rtt/ &&
  npm install -g binci &&
  sed -i 's/rtt:rtt/root:root/g' binci.yml
script:
  - binci test
  - binci doc
  - binci jar
