language: node_js
node_js:
  - node
services: docker
sudo: false

before_install: cd ../ && mv RedditToTelegram rtt/ && cd rtt/ && npm install -g binci
script:
  - binci test
  - binci doc
  - binci jar
