version: '2'

services:
   bot:
     build: ./
     env_file:
       - bot-variables.env
     volumes:
       - subscriptions:/usr/src/app/.data/subscriptions
     restart: always

volumes:
    subscriptions:
