version: '2'

services:
   database:
     image: redis
     volumes:
       - db_data:/data
     restart: always
   bot:
     depends_on:
       - database
     links:
       - database
     build: ./
     env_file:
       - bot-variables.env

volumes:
  db_data: